image: docker/compose:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose -f docker-compose.test.yaml up --build
