image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker ps -a
    - apk add --no-cache docker-compose
    - docker-compose up --build