image: docker:dind

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info
  - apk update
  - apk add --no-cache docker-cli python3
  - apk add --no-cache --virtual .docker-compose-deps python3-dev libffi-dev openssl-dev gcc libc-dev make
  - pip3 install docker-compose
  - apk del .docker-compose-deps

build:
  stage: build
  script:
    - docker-compose up --build
