image: docker:dind

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info
  - apk update
  - apk add python3 python3 py3-pip python3-dev
  - apk add --virtual .docker-compose-deps python3-dev libffi-dev openssl-dev gcc libc-dev make 
  - pip3 install docker-compose
  - apk del .docker-compose-deps

build:
  stage: build
  script:
    - docker-compose -f docker-compose.test.yaml up --build
