version: "3.8"
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks: 
            - app-networks

    observer:
        container_name: observer
        build: ./observer
        volumes:
            - ./observer:/observer
            - share-log:/observer/log
        depends_on: 
            - rabbitmq
        links:
            - rabbitmq
        networks:
            - app-networks
        environment: 
            - MESSAGE_QUEUE=amqp://rabbitmq

    original:
        container_name: original
        build: ./original
        volumes:
            - ./original:/original
            - share-log:/original/log
            - state-db:/original/state-db
        restart: on-failure
        depends_on: 
            - rabbitmq
        links:
            - rabbitmq
        networks:
            - app-networks
        environment: 
            - MESSAGE_QUEUE=amqp://rabbitmq

    intermediate:
        container_name: intermediate
        build: ./intermediate
        volumes:
            - ./intermediate:/intermediate
        restart: on-failure
        depends_on: 
            - rabbitmq
        links:
            - rabbitmq
        networks:
            - app-networks
        environment: 
            - MESSAGE_QUEUE=amqp://rabbitmq
    
    httpenv:
        container_name: httpenv
        build: ./httpenv
        ports:
            - "8081:8081"
        volumes:
            - ./httpenv:/httpenv
            - share-log:/httpenv/api/log/share:ro
            - state-db:/httpenv/api/state-db:ro
        depends_on: 
            - rabbitmq
        links:
            - rabbitmq
        networks:
            - app-networks
        environment: 
            - MESSAGE_QUEUE=amqp://rabbitmq

    gitlab-web:
        image: gitlab/gitlab-ce:latest
        container_name: gitlab-web
        hostname: gitlab-web
        volumes:
            - './gitlab-config:/etc/gitlab'
            - './gitlab-logs:/var/log/gitlab'
            - './gitlab-data:/var/opt/gitlab'
        ports:
            - '2222:22'
            - '8080:80'
            - '443:443'
            - '4567:4567'
        networks:
            - gitlab-network

    gitlab-runner1:
        image: gitlab/gitlab-runner:latest
        container_name: gitlab-runner1
        hostname: gitlab-runner1
        volumes:
            - './gitlab-runner1-config:/etc/gitlab-runner:Z'
            - '/var/run/docker.sock:/var/run/docker.sock'
        networks:
            - gitlab-network


volumes:
    nodemodules: 
    share-log:
    state-db:

networks: 
    app-networks:
        driver: bridge
    gitlab-network:
        name: gitlab-network
