version: "3"
services:
    web-server1:
        build: ./server1
        ports:
            - "8001:8002"
        networks: 
            - testing_net

    web-server2:
        build: ./server2
        networks:
            testing_net:
                ipv4_address: 172.28.0.5
                

networks: 
    testing_net:
        driver: bridge
        ipam:
            driver: default
            config: 
                - subnet: 172.28.0.0/16
                  gateway: 172.28.1.1
